[Settings]
text_font_size = 16
text_font_color = "#FF007F"
capture_frequency = "標準 (2 秒)"
google_cloud_key_file_path = "c:\\Users\\SMH64\\test\\Pyinstaller_test\\manifest-surfer-400014-b04707cc60d4.json"
